### ISSUE TITLE
Add support of custom working directory

### ISSUE THREAD

**Issue by Sergey-Terekhin** [fwinkelbauer/Bumpy#20]
Please add new command line parameter which will specify custom working directory instead of current. It will be useful for processing specific subdirs etc.

**Comment by fwinkelbauer** [comment]
Hey! Thanks for the idea - can you please give me a little bit more input on what exactly you would like to achieve? Of the top of my hat I can think of two different concepts:

**Idea 1**

Call Bumpy with a sub directory relative to the current directory (and use the `.bumpyconfig` of the current directory):

```
C:\MyProject\bumpyconfig
C:\MyProject\MySubDir\...
```

or

**Idea 2**

Call Bumpy with a directory in which a `.bumpyconfig` file is located:

```
C:\SomeAbsolutFolder\MyProject\MySubDir\.bumpyconfig
```

**Comment by Sergey-Terekhin** [comment]
Hi!
I think, it would be better if user can call Bumpy with parameters:
- path to `.bumpyconfig` file
- path to directory to process

If some default values wiil be provided (as current behaviour) it would be good

**Comment by fwinkelbauer** [comment]
That sounds good and reasonable. I will include this in a future version - I just have to deal with some other commitments first.

Thanks again for the idea!

**Comment by fwinkelbauer** [comment]
Just a quick heads up. I'm nearly done with the command line interface redesign. In the future commands like this will be available:

```
bumpy list

// -d -> path to directory
// this will use the configuration file in the current working directory, NOT the one specified in -d
bumpy list -d C:\my_project

// -c -> path to configuration
bumpy list -d C:\my_project -c C:\my_project\.bumpyconfig

// -p -> some profile
bumpy list -p my_profile
```

I have also have to update the Cake addin `Cake.Bumpy` but you can expect a release soon :)
