### ISSUE TITLE
Allow incrementing single component

### ISSUE THREAD

**Issue by euronay** [fwinkelbauer/Bumpy#24]
Hi Florian 

I have a requirement where I need to be able to increment a single component in a version without incrementing the next one. So, for example, `bumpy increment 3` on `2.9.10.1` would produce `2.9.11.1` rather than `2.9.11.0`.

I'm happy to make the change and submit a pull request, but I wanted to get in touch first to get your thoughts on how best to do this. 

My first thoughts would be to either add an extra flag onto the increment command - e.g. `bumpy increment 3 onlythis`; 
or make a new command specifically for this scenario - e.g.:
`bumpy incrementonly 3`

What do you think?

Many Thanks

James

**Comment by fwinkelbauer** [comment]
Hey James,

thank you for your suggestion! Adding a new command would be the easiest solution in terms of writing the actual code, but I believe that a new option (something like `-only`) would offer a "better user experience". A new option could also be utilized in the `assign` command.

I would be happy to receive a pull request if you would like to contribute. Some of the best classes to start would be [BumpyVersion](https://github.com/fwinkelbauer/Bumpy/blob/master/Source/Bumpy/Version/BumpyVersion.cs), [CommandsParser](https://github.com/fwinkelbauer/Bumpy/blob/master/Source/Bumpy/Command/CommandsParser.cs) and [Commands](https://github.com/fwinkelbauer/Bumpy/blob/master/Source/Bumpy/Command/Commands.cs). Let me know if I can help!

**Comment by euronay** [comment]
Thanks, Florian

I'll start working on this in the next couple of days. I'll go with adding a `-only` option to the `Increment` command.

**Comment by euronay** [comment]
Sorry, hit wrong button!

**Comment by fwinkelbauer** [comment]
Your request made me think. Overall I could do a better job in my design to make new features easy to implement. One the one hand I don't want Bumpy to get bloated, on the other hand my ambition has sparked. I am thinking about making Bumpy extensible, but I can neither tell you if this will really happen, nor can I give a timeline.

Because of this thought process I suggest that your feature should be a new command. I cannot think of a better name than your suggested `incrementonly`, sorry!

What do you think?

**Comment by euronay** [comment]
I'll go with `incrementonly` then. It's not the best name in the world but it will do for now!

**Comment by fwinkelbauer** [comment]
So I finally got around to ship this. I'll update Cake.Bumpy in a few days!

**Comment by euronay** [comment]
Awesome! Thanks, Florian 😀
