### ISSUE TITLE
Leading zeros in version number

### ISSUE THREAD

**Issue by euronay** [fwinkelbauer/Bumpy#26]
Hi Florian, me again!

I've found a bug where I have some source files with the version in the format 02.09.0013, which I would like to replace with 2.10.0.  I set up a regex of \d+\.\d+\.\d+ and this matched the expression correctly (using bumpy list found the string), but the text replacement did not work as it was trying to find and replace "2.9.13".

I've made a fix for this. PR is incoming 🚀

Also it might be useful to be able to optionally define the format for version number to be written as. So you could increment 02.09.0013 to 02.09.0014 rather than 2.9.14. I don't need this, but if you are doing a rewrite it might be worth considering.

**Comment by fwinkelbauer** [comment]
Hey James,

that's indeed a good catch. I have never considered versions which contain leading zeros. While I get that your only goal is to fix the replace operation, the PR would create an inconsistency between the commands. Do you need an "offical" updated Bumpy version from NuGet soon, or could you work with your own fork for a while? I've had a few other things on my mind the last weeks, but I am planning to get back to the project this week.

**Comment by euronay** [comment]
Thanks for your feedback. I can work with my fork for a while, no problem at all - I appreciate you probably have other things to worry about!

**Comment by fwinkelbauer** [comment]
I appreciate your effort! I'll keep you updated :).

**Comment by fwinkelbauer** [comment]
My rewrite progress can be seen [here](https://github.com/fwinkelbauer/Bumpy/commits/rewrite).

Of the top of my head I came up with this idea regarding the leading zero issue:

I will try to extend the `BumpyVersion` constructor to take a new argument, which defines the total length of a number for each position. The version parser code would detect these leading zeros and finally, the `ToString` method of `BumpyVersion` will use this property to properly format the version string. I still have to test this, but this **might** work...

**Comment by fwinkelbauer** [comment]
Hi James,

I came up with a draft regarding this issue. If you find the time I'd appreciate it if you could checkout the commit to make sure that Bumpy behaves as it should. I hope that I can ship a new version soon!

**Comment by euronay** [comment]
Just checked this out and it it working great 👌. Thanks!

**Comment by fwinkelbauer** [comment]
Glad to hear that! I'll create a release either today or tomorrow.

I hope that the code is more readable than before. I have decided against trying to implement some fancy extension stuff and I'll instead just see what I can do if people come up with new features/suggestions in the future.

I'll close this issue if the release is done. Thanks!

**Comment by fwinkelbauer** [comment]
🚀
